output   = "dbmodels"
wipe     = true
no-tests = true
pkgname = "dbmodels"
add-soft-deletes = true
add-global-variants = true

[psql]
  dbname = "saaskit"
  host   = "localhost"
  port   = 5433
  user   = "admin"
  pass   = "admin"
  schema = "public"
  sslmode = "disable"
  blacklist = ["schema_migrations"]
